remote_theme: pages-themes/cayman@v0.2.0
gem "github-pages", group: :jekyll_plugins
title: [Alaa Sedeeq]
description: [My Personal Website]
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
